services:
  - type: web
    name: shree-tts
    env: node
    buildCommand: >
      apt-get update && apt-get install -y ffmpeg python3-pip python3-dev espeak libsndfile1 &&
      python3 -m pip install --upgrade pip &&
      python3 -m pip install TTS &&
      mkdir -p .models &&
      python3 -m TTS.bin.list_models &&
      python3 -m TTS.bin.tts --text "Downloading models for Coqui TTS" --model_name tts_models/en/ljspeech/glow-tts --out_path test_ljspeech.wav &&
      python3 -m TTS.bin.tts --text "Testing VCTK model" --model_name tts_models/en/vctk/vits --speaker_idx p273 --out_path test_vctk.wav &&
      npm install
    startCommand: npm run start-render
    envVars:
      # Optional API keys for enhanced features
      - key: OPENAI_API_KEY
        sync: false
        required: false
      - key: HUGGING_FACE_API_KEY
        sync: false
        required: false
      - key: PORT
        value: 10000
      # Add Coqui environment variables
      - key: VIRTUAL_ENV
        value: /opt/render/project
      - key: RENDER
        value: "true"
      # Firebase Client Configuration
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      # Firebase Admin Configuration
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false 