services:
  - type: web
    name: voicecraft-tts
    env: node
    plan: free
    buildCommand: >
      apt-get update && apt-get install -y ffmpeg python3-pip python3-dev espeak espeak-ng libsndfile1 &&
      pip3 install TTS==0.22.0 && 
      chmod +x download-models.sh && ./download-models.sh &&
      npm install
    startCommand: node render-server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: RENDER
        value: "true"
      - key: PORT
        value: 3001
      - key: VIRTUAL_ENV
        value: /opt/render/project
      - key: TTS_CACHE_DIR
        value: "/opt/render/project/.models"
    autoDeploy: true
    envVars:
      # Optional API keys for enhanced features
      - key: OPENAI_API_KEY
        sync: false
        required: false
      - key: HUGGING_FACE_API_KEY
        sync: false
        required: false
      # Firebase Client Configuration
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      # Firebase Admin Configuration
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false 